### ISSUE TITLE
Include splitSimVBF.cpp in VERITAS-Observatory version of EventDisplay

### ISSUE THREAD

**Issue by dawucsc** [VERITAS-Observatory/EventDisplay_v4#247]
It would be good to include splitSimVBF.cpp, which is in the [EventDisplay organization version of the code](https://github.com/Eventdisplay/Eventdisplay/blob/main/src/splitSimVBF.cpp) in the VERITAS-Observatory version as well.  People are more likely to be looking for it in the VERITAS version, since it is specific to VERITAS needs.

**Comment by jodiC** [comment]
It would be good to include a target for making the splitSimVBF in the Makefile.  I compiled from the tagged version Eventdisplay-2.5.10.


On Sep 16, 2023, at 9:50 AM, David Williams ***@***.***> wrote:



It would be good to include splitSimVBF.cpp, which is in the EventDisplay organization version of the code<https://github.com/Eventdisplay/Eventdisplay/blob/main/src/splitSimVBF.cpp> in the VERITAS-Observatory version as well. People are more likely to be looking for it in the VERITAS version, since it is specific to VERITAS needs.

**Comment by GernotMaier** [comment]
Not sure what the issue is:

- [splitSimVBF](https://github.com/VERITAS-Observatory/EventDisplay_v4/blob/main/src/splitVBF.cpp) is part of the VERITAS-specific Eventdisplay code.
- there is a Makefile target, see [here](https://github.com/VERITAS-Observatory/EventDisplay_v4/blob/05f124fcd9f8c69b723c9cedacbb664ac77f2efc/Makefile#L545). I've just tried `make splitVBF` and it compiles successfully.

Note that I am not aware of any use cases for splitVBF for Eventdisplay users.

What is Eventdisplay-2.5.10? That doesn't appear in my list of tags or releases (https://github.com/VERITAS-Observatory/EventDisplay_v4/tags)

**Comment by dawucsc** [comment]
This issue is about splitSimVBF, not splitVBF.  splitSimVBF is a variant of splitVBF that was introduced to split simulations files in a way that is compatible with VEGAS.

**Comment by GernotMaier** [comment]
Would it make sense to have this code in VEGAS? This seems really to be VEGAS specific (or needed) and I think we don't have a use case on the Eventdisplay side. Generally, code which is not used within Eventdisplay use cases disappears with time.

**Comment by dawucsc** [comment]
You do have a use case on the eventDisplay side, because you have used splitVBF when processing simulations, and we have to merge them and resplit them to process them with VEGAS.   If you would reread the first post in this issue carefully, you have the code already in the general EventDisplay repository.  It is just a matter adding it to the VERITAS-Observatory one.

**Comment by GernotMaier** [comment]
Could you explain a bit in more detail where we use splitVBF? I am missing something, but we definitely don't use it when analysing simulations files (or do you mean in the simulation production?). Also if we split, do we split them in a wrong way if you have to merge and split them again?

**Comment by dawucsc** [comment]
Yes, you use it in simulation production.  And if the simulations are split with splitVBF, they don't work with VEGAS and they have to be merged and resplit.  Note the comment on the second line of splitVBF.  It says that splitSimVBF should be used for simulation files, but splitSimVBF is not in the repository.

**Comment by GernotMaier** [comment]
Apologies, haven't been involved in the simulation production since a long time and I've never used any of the splitting tools. Is this for the Grisu or CARE productions?

Trying to understand the small differences between the two tools. Is it that the first event shouldn't be a pedestal event?

What about adding those tools to VEGAS if there are mostly important for the VEGAS analysis? Code for which there is no use case in Eventdisplay will always have the tendency to disappear (we've removed 1000s of lines of code in the past year of obsolete code to simplify maintenance).
